# Generated by Django 5.2.7 on 2025-10-11 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_remove_propiedad_imagen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='telefono_contacto',
            field=models.CharField(blank=True, help_text='Número de WhatsApp del propietario', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='banos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='habitaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='metros_cuadrados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='publicada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL),
        ),
    ]
