# Generated by Django 5.2.5 on 2025-11-09 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_product_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
